services:
  postgres-db-main:
    image: postgres:16-alpine
    container_name: postgres-db-main
    environment:
      POSTGRES_DB: ${DB_MAIN}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_MAIN}"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-db-test:
    image: postgres:16-alpine
    container_name: postgres-db-test
    environment:
      POSTGRES_DB: ${DB_TEST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_TEST}"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastify-api:
    container_name: ${PROJECT_NAME}-fastify-api
    build: 
      context: .
      dockerfile: apps/fastify-api/Dockerfile
    command: npx tsx watch apps/fastify-api/src/index.ts
    restart: on-failure
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: ${DB_MAIN_URL}
      
      INNGEST_EVENT_KEY: v1_your_key
    depends_on:
      postgres-db-main:
        condition: service_healthy
    volumes:
      - .:/app

  inngest:
    image: inngest/inngest
    container_name: ${PROJECT_NAME}-inngest
    restart: unless-stopped
    ports:
      - "8288:8288"
    command: ["inngest", "dev", "-u", "http://fastify-api:3005/api/inngest"]
    depends_on:
      - fastify-api

volumes:
  postgres_main_data: {}
  postgres_test_data: {}
  